# Generated by Django 3.1.4 on 2022-01-14 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manager',
            new_name='Agent',
        ),
    ]
