# Generated by Django 3.1.4 on 2022-01-14 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20220114_0708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='manager',
            new_name='agent',
        ),
    ]
